// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const chrome = require('selenium-webdriver/chrome');

describe('222', function() {
   this.timeout(30000)
  let driver
  let vars
  let options
  beforeEach(async function() {
    options = new chrome.Options()
    options.setBinaryPath("C:\\Users\\Anton\\Bin\\chromedriver\\chrome.exe");
    driver = await new Builder().forBrowser('chrome').setChromeOptions(options).build()
    vars = {}
  });
  afterEach(async function() {
    await driver.quit();
  })
  it('222', async function() {
    // Test name: 222
    // Step # | name | target | value
    // 1 | open | /documentation/ | 
    await driver.get("https://www.selenium.dev/documentation/")
    // 2 | setWindowSize | 1536x816 | 
    await driver.manage().window().setRect({ width: 1536, height: 816 })
    // 3 | click | css=#docsearch-1 .DocSearch-Button-Placeholder | 
    await driver.findElement(By.css("#docsearch-1 .DocSearch-Button-Placeholder")).click()
    // 4 | click | id=docsearch-input | 
    await driver.findElement(By.id("docsearch-input")).click()
    // 5 | type | id=docsearch-input | webdriver
    await driver.findElement(By.id("docsearch-input")).sendKeys("webdriver")
    // 6 | sendKeys | id=docsearch-input | ${KEY_ENTER}
    await driver.findElement(By.id("docsearch-input")).sendKeys(Key.ENTER)
    
    assert.equal(await driver.getTitle(), "WebDriver | Selenium");
    //expect(await driver.getTitle()).toEqual('WebDriver | Selenium');
  })
});
