// Generated by Selenium IDE
const { Builder, Browser, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const Chrome = require('selenium-webdriver/chrome');

xdescribe('Google Search', function () {
  it('should work', async function () {
    // this.timeout(30000)
    let vars
    const options = new Chrome.Options();
    options.addArguments("--no-sandbox", "--verbose", "--log-path=C:\\Users\\Anton\\Bin\\chromedriver.log")
      .setBinaryPath("C:\\Users\\Anton\\Bin\\chromedriver\\chrome.exe");


    let driver = await new Builder()
      .forBrowser(Browser.CHROME)
      .setChromeOptions(options)
      .build();



    await driver.get("https://www.selenium.dev/documentation/webdriver/getting_started/first_script/");
     await driver.manage().window().setRect({ width: 1536, height: 816 });
    await driver.findElement(By.css("#docsearch-1 .DocSearch-Button-Placeholder")).click();
    // {
    //   const element = await driver.findElement(By.css("#docsearch-1 .DocSearch-Button-Placeholder"))
    //   await driver.actions({ bridge: true }).moveToElement(element).perform()
    // }
    // {
    //   const element = await driver.findElement(By.CSS_SELECTOR, "body")
    //   await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    // }
    await driver.findElement(By.id("docsearch-input")).click();
    await driver.findElement(By.id("docsearch-input")).sendKeys("webdriver");
    await driver.findElement(By.css("#docsearch-item-0 .DocSearch-Hit-title")).click();
   
  });
},30000);
