// Generated by Selenium IDE
const { Builder, Browser, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const Chrome = require('selenium-webdriver/chrome');

describe('Google Search', function () {
  it('should work', async function () {
    // this.timeout(30000)
    let vars
    const options = new Chrome.Options();
    options.addArguments("--no-sandbox", "--verbose", "--log-path=C:\\Users\\Anton\\Bin\\chromedriver.log")
      .setBinaryPath("C:\\Users\\Anton\\Bin\\chromedriver\\chrome.exe");


    let driver = await new Builder()
      .forBrowser(Browser.CHROME)
      .setChromeOptions(options)
      .build();


    try {
      await driver.get("https://www.selenium.dev/documentation");
      await driver.findElement(By.className("DocSearch")).click();
      await driver.findElement(By.className("DocSearch-Input")).click();
      await driver.findElement(By.className("DocSearch-Input")).sendKeys("webdriver");
      await driver.findElement(By.className("DocSearch-Input")).submit();
      await driver.wait(until.elementLocated(By.className("DocSearch-Hit-title")));

      await driver.findElement(By.className("DocSearch-Input")).sendKeys(Key.ENTER);
     
      await driver.wait(until.titleContains('WebDriver | Selenium'));

      expect(await driver.getTitle()).toEqual('WebDriver | Selenium');
    } finally {
      //await driver.quit();
    }
  }, 30000);
}, 30000);
